/**
 * Dashboard — Hooke
 *
 * All data comes from real stores or the in-session event bus.
 * No hardcoded counts, names, or activity feed entries.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useEffect, useRef } from "react";
import {
  Activity,
  Clapperboard,
  FolderKanban,
  Plus,
  Settings,
  Sparkles,
  Upload,
  Film,
  Play,
  HardDrive,
} from "lucide-react";
import { useProjectStore } from "@/store/project-store";
import { useBlueprintStore, STRATEGY_PRESETS } from "@/store/blueprint-store";
import { useAssetStore } from "@/store/asset-store";
import { useStoryStore } from "@/store/story-store";
import { useSettingsStore } from "@/store/settings-store";
import { eventBus } from "@/lib/platform/event-bus";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — Hooke" },
      {
        name: "description",
        content:
          "Overview of your Hooke workspace: projects, interviews, assets, and session activity.",
      },
      { property: "og:title", content: "Dashboard — Hooke" },
    ],
  }),
  component: DashboardPage,
});

/* ─── Activity hook (session-scoped, real events only) ──────────────────── */

type ActivityItem = {
  id: string;
  Icon: React.ElementType;
  color: string;
  text: string;
  at: number;
};

function useSessionActivity(): ActivityItem[] {
  const [items, setItems] = useState<ActivityItem[]>([]);
  const counterRef = useRef(0);

  useEffect(() => {
    const push = (item: Omit<ActivityItem, "id">) =>
      setItems((prev) =>
        [{ ...item, id: `a_${++counterRef.current}` }, ...prev].slice(0, 30),
      );

    const unsubs = [
      eventBus.on("blueprint:generated", () =>
        push({ Icon: Sparkles, color: "var(--accent-iris)", text: "Blueprint generated by miDirector", at: Date.now() }),
      ),
      eventBus.on("project:created", (e) =>
        push({ Icon: FolderKanban, color: "var(--accent-mint)", text: `Project created`, at: Date.now() }),
      ),
      eventBus.on("project:updated", () =>
        push({ Icon: FolderKanban, color: "var(--accent-mint)", text: "Project updated", at: Date.now() }),
      ),
      eventBus.on("asset:added", (e) =>
        push({ Icon: Upload, color: "var(--accent-mint)", text: `Asset imported (${e.kind})`, at: Date.now() }),
      ),
      eventBus.on("asset:removed", () =>
        push({ Icon: Upload, color: "var(--accent-ember)", text: "Asset removed", at: Date.now() }),
      ),
      eventBus.on("story:created", () =>
        push({ Icon: Clapperboard, color: "var(--accent-gold)", text: "New series created", at: Date.now() }),
      ),
      eventBus.on("ai:generation:started", (e) =>
        push({ Icon: Sparkles, color: "var(--accent-iris)", text: `AI generation started — ${e.agent}`, at: Date.now() }),
      ),
      eventBus.on("ai:generation:completed", (e) =>
        push({ Icon: Sparkles, color: "var(--accent-mint)", text: `AI generation completed — ${e.agent}`, at: Date.now() }),
      ),
      eventBus.on("ai:generation:failed", (e) =>
        push({ Icon: Activity, color: "var(--accent-ember)", text: `Generation failed — ${e.agent}: ${e.error.slice(0, 60)}`, at: Date.now() }),
      ),
      eventBus.on("settings:provider:updated", (e) =>
        push({ Icon: HardDrive, color: "var(--accent-gold)", text: `AI provider ${e.action} — ${e.provider}`, at: Date.now() }),
      ),
    ];

    return () => unsubs.forEach((u) => u());
  }, []);

  return items;
}

/* ─── Helpers ───────────────────────────────────────────────────────────── */

function fmtRelative(ms: number): string {
  const diff = (Date.now() - ms) / 1000;
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

/* ─── Page ───────────────────────────────────────────────────────────────── */

function DashboardPage() {
  const projects = useProjectStore((s) => s.projects);
  const conversations = useBlueprintStore((s) => s.conversations);
  const assets = useAssetStore((s) => s.assets);
  const series = useStoryStore((s) => s.series);
  const activity = useSessionActivity();

  const activeProjects = projects.filter((p) => p.status !== "archived").length;
  const blueprintCount = conversations.filter((c) => c.blueprint).length;
  const assetCount = assets.length;
  const seriesCount = series.length;

  return (
    <div className="mx-auto flex w-full max-w-[1480px] flex-col gap-5">
      {/* Stat row */}
      <div className="grid grid-cols-2 gap-3.5 lg:grid-cols-4">
        <StatCard
          accent="iris"
          label="Projects"
          value={String(activeProjects)}
          sub={activeProjects === 1 ? "1 active" : `${activeProjects} active`}
          icon={<FolderKanban className="h-8 w-8" />}
        />
        <StatCard
          accent="mint"
          label="Blueprints"
          value={String(blueprintCount)}
          sub={`${conversations.length} interview${conversations.length !== 1 ? "s" : ""}`}
          icon={<Sparkles className="h-8 w-8" />}
        />
        <StatCard
          accent="gold"
          label="Assets"
          value={String(assetCount)}
          sub={assetCount === 0 ? "nothing imported yet" : `${assetCount} file${assetCount !== 1 ? "s" : ""}`}
          icon={<Upload className="h-8 w-8" />}
        />
        <StatCard
          accent="ember"
          label="Series"
          value={String(seriesCount)}
          sub={seriesCount === 0 ? "none yet" : `${seriesCount} story thread${seriesCount !== 1 ? "s" : ""}`}
          icon={<Film className="h-8 w-8" />}
        />
      </div>

      {/* miDirector hero panel */}
      <DirectorPanel conversationCount={conversations.length} />

      {/* Main grid */}
      <div className="grid grid-cols-1 gap-3.5 lg:grid-cols-[2fr_1fr]">
        <RecentProjectsCard projects={projects} />
        <ActivityFeedCard items={activity} />
      </div>

      <div className="grid grid-cols-1 gap-3.5 lg:grid-cols-[1fr_2fr]">
        <QuickActionsCard />
        <PlatformStatusCard />
      </div>
    </div>
  );
}

/* ─── Stat Card ─────────────────────────────────────────────────────────── */

function StatCard({
  accent,
  label,
  value,
  sub,
  icon,
}: {
  accent: "iris" | "mint" | "ember" | "gold";
  label: string;
  value: string;
  sub: string;
  icon: React.ReactNode;
}) {
  const colorVar =
    accent === "iris"
      ? "var(--accent-iris)"
      : accent === "mint"
        ? "var(--accent-mint)"
        : accent === "ember"
          ? "var(--accent-ember)"
          : "var(--accent-gold)";
  return (
    <div className="hk-card hk-card-hover relative overflow-hidden px-[18px] py-4">
      <div
        className="absolute left-0 right-0 top-0 h-[2px]"
        style={{ background: `linear-gradient(90deg, ${colorVar}, transparent)` }}
      />
      <div className="mb-2 text-[11.5px] font-medium uppercase tracking-[0.3px] text-text-secondary">
        {label}
      </div>
      <div className="hk-text-display mb-1.5 text-[28px] font-bold leading-none text-text-primary">
        {value}
      </div>
      <div className="text-[11.5px] font-medium text-text-secondary">{sub}</div>
      <div className="absolute bottom-3.5 right-4 opacity-10" style={{ color: colorVar }}>
        {icon}
      </div>
    </div>
  );
}

/* ─── miDirector panel ──────────────────────────────────────────────────── */

function DirectorPanel({ conversationCount }: { conversationCount: number }) {
  return (
    <section
      className="overflow-hidden rounded-[20px] border hk-glow-iris"
      style={{
        background: "linear-gradient(135deg, var(--bg-surface) 0%, var(--bg-elevated) 100%)",
        borderColor: "rgba(108,99,255,0.2)",
      }}
    >
      <header
        className="flex items-center gap-3 border-b px-[22px] py-4"
        style={{
          background: "var(--gradient-director)",
          borderColor: "rgba(108,99,255,0.15)",
        }}
      >
        <div
          className="flex h-[38px] w-[38px] shrink-0 items-center justify-center rounded-[10px]"
          style={{ background: "var(--gradient-iris)" }}
        >
          <Clapperboard className="h-[18px] w-[18px] text-white" />
        </div>
        <div className="flex-1">
          <div className="hk-text-display text-[15px] font-bold text-text-primary">miDirector</div>
          <div className="mt-px text-[12px] text-text-secondary">
            Conversational AI that translates your intent into a shootable blueprint.
          </div>
        </div>
        {conversationCount > 0 && (
          <div className="text-[11px] text-text-dim">
            {conversationCount} interview{conversationCount !== 1 ? "s" : ""}
          </div>
        )}
      </header>

      <div className="px-[22px] py-5">
        <div className="mb-4 grid grid-cols-2 gap-2.5 lg:grid-cols-3 xl:grid-cols-6">
          {STRATEGY_PRESETS.map((p) => (
            <Link
              key={p.id}
              to="/director"
              className="rounded-[10px] border border-white/10 bg-base/60 p-3 text-left transition-colors hover:border-iris/60 hover:bg-elevated"
            >
              <div className="text-[13px] font-semibold text-text-primary">{p.name}</div>
              <div className="mt-0.5 text-[11px] leading-snug text-text-secondary">{p.blurb}</div>
            </Link>
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Link
            to="/director"
            className="inline-flex items-center gap-2 rounded-md px-4 py-2 text-[13px] font-semibold text-white transition-opacity hover:opacity-90"
            style={{ background: "var(--gradient-iris)" }}
          >
            <Play className="h-3.5 w-3.5" />
            Start Interview
          </Link>
          {conversationCount === 0 && (
            <span className="text-[12px] text-text-dim">
              No interviews yet — start one above.
            </span>
          )}
        </div>
      </div>
    </section>
  );
}

/* ─── Recent Projects ───────────────────────────────────────────────────── */

import type { Project } from "@/store/project-store";

const STATUS_LABEL: Record<string, string> = {
  draft: "Draft",
  active: "Active",
  published: "Published",
  archived: "Archived",
};

const STATUS_COLOR: Record<string, string> = {
  draft: "text-text-dim",
  active: "text-mint",
  published: "text-iris",
  archived: "text-text-dim",
};

function RecentProjectsCard({ projects }: { projects: Project[] }) {
  const visible = [...projects]
    .filter((p) => p.status !== "archived")
    .sort((a, b) => b.updatedAt - a.updatedAt)
    .slice(0, 5);

  return (
    <div className="hk-card">
      <CardHeader title="Recent Projects">
        <Link
          to="/projects"
          className="text-[11.5px] text-text-secondary hover:text-iris transition-colors"
        >
          View all
        </Link>
      </CardHeader>

      {visible.length === 0 ? (
        <div className="flex flex-col items-center gap-3 px-[18px] py-10 text-center">
          <FolderKanban className="h-8 w-8 text-text-dim opacity-40" />
          <div className="text-[13px] text-text-secondary">No projects yet</div>
          <Link
            to="/projects"
            className="inline-flex h-8 items-center gap-1.5 rounded-md border border-iris/40 bg-iris/10 px-3 text-[12px] font-medium text-iris hover:bg-iris/20"
          >
            <Plus className="h-3 w-3" />
            Create your first project
          </Link>
        </div>
      ) : (
        <div className="divide-y divide-white/[0.06]">
          {visible.map((p) => (
            <div key={p.id} className="flex items-center gap-3 px-[18px] py-3.5">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-elevated text-text-secondary">
                <FolderKanban className="h-4 w-4" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="truncate text-[13.5px] font-medium text-text-primary">
                  {p.name}
                </div>
                <div className="mt-0.5 text-[11px] text-text-dim">
                  {fmtRelative(p.updatedAt)}
                </div>
              </div>
              <span className={`text-[11.5px] font-medium ${STATUS_COLOR[p.status] ?? "text-text-dim"}`}>
                {STATUS_LABEL[p.status] ?? p.status}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/* ─── Activity Feed ─────────────────────────────────────────────────────── */

function ActivityFeedCard({ items }: { items: ActivityItem[] }) {
  return (
    <div className="hk-card">
      <CardHeader title="Session Activity">
        <span className="h-1.5 w-1.5 rounded-full bg-mint shadow-[0_0_6px_var(--accent-mint)]" />
      </CardHeader>

      {items.length === 0 ? (
        <div className="flex flex-col items-center gap-2 px-[18px] py-10 text-center">
          <Activity className="h-7 w-7 text-text-dim opacity-30" />
          <div className="text-[12.5px] text-text-secondary">No activity yet this session</div>
          <div className="text-[11px] text-text-dim">
            Actions like creating projects, importing assets, and generating blueprints will appear here.
          </div>
        </div>
      ) : (
        <div className="px-[18px] py-2">
          {items.slice(0, 8).map((a) => {
            const Icon = a.Icon;
            return (
              <div key={a.id} className="flex items-start gap-3 py-2.5">
                <div
                  className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md"
                  style={{ background: "rgba(255,255,255,0.04)", color: a.color }}
                >
                  <Icon className="h-3.5 w-3.5" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="truncate text-[13px] text-text-primary">{a.text}</div>
                  <div className="mt-0.5 text-[11px] text-text-dim">{fmtRelative(a.at)}</div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

/* ─── Quick Actions ─────────────────────────────────────────────────────── */

function QuickActionsCard() {
  const actions = [
    { to: "/projects", icon: Plus, label: "New Project", accent: "iris" as const },
    { to: "/director", icon: Clapperboard, label: "Start Interview", accent: "mint" as const },
    { to: "/assets", icon: Upload, label: "Import Assets", accent: "ember" as const },
    { to: "/settings", icon: Settings, label: "Settings", accent: "gold" as const },
  ];
  return (
    <div className="hk-card">
      <CardHeader title="Quick Actions" />
      <div className="grid grid-cols-2 gap-2.5 p-[18px]">
        {actions.map((a) => {
          const Icon = a.icon;
          return (
            <Link
              key={a.label}
              to={a.to}
              className="hk-card-hover flex flex-col items-start gap-2.5 rounded-[10px] border border-white/[0.06] bg-elevated p-3.5 transition-colors hover:border-white/20"
            >
              <div
                className="flex h-9 w-9 items-center justify-center rounded-md"
                style={{
                  background: `color-mix(in oklab, var(--accent-${a.accent}) 18%, transparent)`,
                  color: `var(--accent-${a.accent})`,
                }}
              >
                <Icon className="h-4 w-4" />
              </div>
              <div className="text-[13px] font-medium text-text-primary">{a.label}</div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}

/* ─── Platform Status ───────────────────────────────────────────────────── */

function PlatformStatusCard() {
  const providers = useSettingsStore((s) => s.providers);
  const hasProvider = providers.length > 0;

  return (
    <div className="hk-card">
      <CardHeader title="Platform Status" />
      <div className="divide-y divide-white/[0.06]">

        {/* AI Providers */}
        <div className="flex items-center gap-3 px-[18px] py-3.5">
          <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-md ${hasProvider ? "bg-mint/15" : "bg-white/[0.04]"}`}>
            <HardDrive className={`h-4 w-4 ${hasProvider ? "text-mint" : "text-text-dim"}`} />
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-[13px] font-medium text-text-primary">AI Providers</div>
            <div className="text-[11px] text-text-secondary">
              {hasProvider
                ? `${providers.length} provider${providers.length !== 1 ? "s" : ""} configured`
                : "No providers configured — add one in Settings"}
            </div>
          </div>
          {!hasProvider && (
            <Link
              to="/settings"
              className="text-[11.5px] text-iris hover:underline"
            >
              Configure
            </Link>
          )}
        </div>

        {/* miDirector */}
        <div className="flex items-center gap-3 px-[18px] py-3.5">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-iris/15">
            <Clapperboard className="h-4 w-4 text-iris" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-[13px] font-medium text-text-primary">miDirector</div>
            <div className="text-[11px] text-text-secondary">
              {hasProvider ? "LLM-powered blueprint generation" : "Local fallback — no LLM provider configured"}
            </div>
          </div>
          <span className={`text-[11px] font-medium ${hasProvider ? "text-mint" : "text-text-dim"}`}>
            {hasProvider ? "Ready" : "Fallback"}
          </span>
        </div>

        {/* Storage */}
        <div className="flex items-center gap-3 px-[18px] py-3.5">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-gold/15">
            <HardDrive className="h-4 w-4 text-gold" style={{ color: "var(--accent-gold)" }} />
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-[13px] font-medium text-text-primary">Local Storage</div>
            <div className="text-[11px] text-text-secondary">
              IndexedDB — data stored on this device only
            </div>
          </div>
          <span className="text-[11px] font-medium text-mint">Active</span>
        </div>

      </div>
    </div>
  );
}

/* ─── Shared ─────────────────────────────────────────────────────────────── */

function CardHeader({
  title,
  children,
}: {
  title: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-center gap-2.5 border-b border-white/[0.06] px-[18px] py-3.5">
      <h3 className="hk-text-display text-[14px] font-semibold text-text-primary">{title}</h3>
      {children && <div className="ml-auto flex items-center gap-2">{children}</div>}
    </div>
  );
}
