/**
 * Hooke Blueprint Engine
 *
 * The single source of truth for project creative intent.
 * A Blueprint drives every downstream AI generation in the platform.
 *
 * The Blueprint Engine:
 *   - Validates blueprint structure (Zod)
 *   - Versions blueprints on every edit
 *   - Registers blueprints in the Project Graph
 *   - Emits platform events on generation and updates
 *   - Stores blueprints in IndexedDB
 *
 * Blueprint GENERATION (calling a real LLM) is performed by the Director Agent.
 * This engine handles storage, validation, versioning, and platform integration.
 */

import { get as idbGet, set as idbSet } from 'idb-keyval';
import { eventBus } from './event-bus';
import { projectGraph } from './project-graph';

// ─── Blueprint Schema ──────────────────────────────────────────────────────

export type StrategyPreset =
  | 'cinematic'
  | 'documentary'
  | 'kinetic'
  | 'product'
  | 'narrative'
  | 'social';

export interface BlueprintScene {
  id: string;
  number: number;
  heading: string;
  beat: string;
  shot: string;
  duration: number; // seconds
  prompt: string;
  /** Which entities from the Project Graph appear in this scene */
  entityRefs?: string[];
}

export interface Blueprint {
  id: string;
  /** Monotonically increasing version number */
  version: number;
  title: string;
  projectId?: string;
  preset: StrategyPreset;
  logline: string;
  audience: string;
  tone: string;
  length: string;
  format: string;
  references: string;
  scenes: BlueprintScene[];
  /** ID of the previous version, if this was generated from an edit */
  parentVersionId?: string;
  createdAt: number;
  updatedAt: number;
}

/** Minimal validation — more complete validation happens at the AI output layer */
export function validateBlueprint(bp: unknown): bp is Blueprint {
  if (typeof bp !== 'object' || bp === null) return false;
  const b = bp as Record<string, unknown>;
  if (typeof b.id !== 'string' || !b.id) return false;
  if (typeof b.title !== 'string') return false;
  if (!Array.isArray(b.scenes)) return false;
  if (b.scenes.length === 0) return false;
  for (const scene of b.scenes as unknown[]) {
    if (typeof scene !== 'object' || scene === null) return false;
    const s = scene as Record<string, unknown>;
    if (typeof s.id !== 'string' || !s.id) return false;
    if (typeof s.heading !== 'string') return false;
  }
  return true;
}

// ─── Storage ───────────────────────────────────────────────────────────────

interface BlueprintStore {
  version: number;
  blueprints: Record<string, Blueprint>;
  /** projectId → current active blueprint ID */
  activeByProject: Record<string, string>;
}

const STORAGE_KEY = 'hooke:blueprint-engine';
const SCHEMA_VERSION = 1;

function emptyStore(): BlueprintStore {
  return { version: SCHEMA_VERSION, blueprints: {}, activeByProject: {} };
}

const uid = () =>
  globalThis.crypto?.randomUUID?.() ??
  `bp_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;

// ─── Blueprint Engine Implementation ──────────────────────────────────────

class BlueprintEngineClass {
  private store: BlueprintStore = emptyStore();
  private loaded = false;

  async load(): Promise<void> {
    try {
      const stored = await idbGet<BlueprintStore>(STORAGE_KEY);
      if (stored && stored.version === SCHEMA_VERSION) {
        this.store = stored;
      }
    } catch {
      this.store = emptyStore();
    }
    this.loaded = true;
  }

  private async persist(): Promise<void> {
    try {
      await idbSet(STORAGE_KEY, this.store);
    } catch (err) {
      console.error('[BlueprintEngine] Failed to persist:', err);
    }
  }

  // ─── Storage & Registration ──────────────────────────────────────────

  /**
   * Store a blueprint generated by the Director Agent.
   * Registers it in the Project Graph and emits blueprint:generated.
   *
   * This is called after the AI returns a valid blueprint, NOT before.
   */
  store_blueprint(
    blueprint: Omit<Blueprint, 'id' | 'version' | 'createdAt' | 'updatedAt'>
  ): Blueprint {
    const now = Date.now();
    const id = uid();
    const full: Blueprint = {
      ...blueprint,
      id,
      version: 1,
      createdAt: now,
      updatedAt: now,
    };

    if (!validateBlueprint(full)) {
      throw new Error('[BlueprintEngine] Blueprint failed validation.');
    }

    this.store.blueprints[id] = full;
    if (full.projectId) {
      this.store.activeByProject[full.projectId] = id;
    }
    void this.persist();

    // Register in Project Graph
    if (full.projectId) {
      projectGraph.registerBlueprint(id, full.projectId, full.title);
    }

    eventBus.emit('blueprint:generated', {
      blueprintId: id,
      projectId: full.projectId ?? '',
      conversationId: '',
    });

    return full;
  }

  // ─── Versioning ──────────────────────────────────────────────────────

  /**
   * Create a new version of an existing blueprint after a user edit.
   * The old version is preserved in the store.
   */
  createVersion(
    blueprintId: string,
    patch: Partial<Omit<Blueprint, 'id' | 'version' | 'createdAt' | 'parentVersionId'>>
  ): Blueprint | undefined {
    const existing = this.store.blueprints[blueprintId];
    if (!existing) return undefined;

    const now = Date.now();
    const newId = uid();
    const newVersion: Blueprint = {
      ...existing,
      ...patch,
      id: newId,
      version: existing.version + 1,
      parentVersionId: blueprintId,
      updatedAt: now,
      createdAt: now,
    };

    this.store.blueprints[newId] = newVersion;
    if (newVersion.projectId) {
      this.store.activeByProject[newVersion.projectId] = newId;
    }
    void this.persist();

    eventBus.emit('blueprint:updated', {
      blueprintId: newId,
      projectId: newVersion.projectId ?? '',
      fields: Object.keys(patch),
    });

    return newVersion;
  }

  // ─── Scene Operations ─────────────────────────────────────────────────

  updateScene(
    blueprintId: string,
    sceneId: string,
    patch: Partial<Omit<BlueprintScene, 'id' | 'number'>>
  ): Blueprint | undefined {
    const bp = this.store.blueprints[blueprintId];
    if (!bp) return undefined;

    const updated: Blueprint = {
      ...bp,
      scenes: bp.scenes.map((s) => (s.id === sceneId ? { ...s, ...patch } : s)),
      updatedAt: Date.now(),
    };
    this.store.blueprints[blueprintId] = updated;
    void this.persist();
    return updated;
  }

  addScene(blueprintId: string, scene: Omit<BlueprintScene, 'id' | 'number'>): Blueprint | undefined {
    const bp = this.store.blueprints[blueprintId];
    if (!bp) return undefined;

    const newScene: BlueprintScene = {
      ...scene,
      id: uid(),
      number: bp.scenes.length + 1,
    };
    const updated: Blueprint = {
      ...bp,
      scenes: [...bp.scenes, newScene],
      updatedAt: Date.now(),
    };
    this.store.blueprints[blueprintId] = updated;
    void this.persist();
    eventBus.emit('blueprint:scene:added', { blueprintId, sceneId: newScene.id });
    return updated;
  }

  removeScene(blueprintId: string, sceneId: string): Blueprint | undefined {
    const bp = this.store.blueprints[blueprintId];
    if (!bp) return undefined;

    const scenes = bp.scenes
      .filter((s) => s.id !== sceneId)
      .map((s, i) => ({ ...s, number: i + 1 }));
    const updated: Blueprint = { ...bp, scenes, updatedAt: Date.now() };
    this.store.blueprints[blueprintId] = updated;
    void this.persist();
    eventBus.emit('blueprint:scene:removed', { blueprintId, sceneId });
    return updated;
  }

  // ─── Retrieval ───────────────────────────────────────────────────────

  getBlueprint(id: string): Blueprint | undefined {
    return this.store.blueprints[id];
  }

  getActiveBlueprintForProject(projectId: string): Blueprint | undefined {
    const id = this.store.activeByProject[projectId];
    return id ? this.store.blueprints[id] : undefined;
  }

  getVersionHistory(blueprintId: string): Blueprint[] {
    const target = this.store.blueprints[blueprintId];
    if (!target) return [];

    const history: Blueprint[] = [target];
    let current = target;
    while (current.parentVersionId) {
      const parent = this.store.blueprints[current.parentVersionId];
      if (!parent) break;
      history.unshift(parent);
      current = parent;
    }
    return history;
  }

  _reset(): void {
    this.store = emptyStore();
  }
}

// ─── Singleton Export ──────────────────────────────────────────────────────

export const blueprintEngine = new BlueprintEngineClass();
